# LAUNCHER CONFIG

# List of DLLs to be injected into the game on launch. Uncomment to use.
# Allows for relative paths as well as aboslute.
# Use either `/` or `\\` for path seperators.
# Example dlls=["c:/path/to/some/mod.dll", "mod.dll"]
dlls = ["..\\gun_game\\target\\debug\\gun_game.dll"]

# List of mod directories
# Allows for relative paths as well as aboslute.
# Use either `/` or `\\` for path seperators.
# Default is set to `mod`
# Example mods=["c:/path/to/mod/dir/", "mod2"]
mods = ["mod"]
